### ISSUE TITLE
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'

### ISSUE THREAD

**Issue by ajoe** [littleyoda/hibiscus_tradeRepublicExporter#3]
Windows 11 CMD, Python 3.11.9

Wenn ich das in der Windows CMD starte bekomme ich den Fehler unten. Das gleiche passiert mit Ubuntu unter Linux (WSL2) und Python 3.12.3

Eine Idee woran es liegen könnte?

```
21:38:46 Connecting to websocket ...
Traceback (most recent call last):
  File "C:\jochen\tradeRepublicExporter\hibiscus_tradeRepublicExporter\tr2hibiscusxml.py", line 130, in <module>
    main()
  File "C:\jochen\tradeRepublicExporter\hibiscus_tradeRepublicExporter\tr2hibiscusxml.py", line 124, in main
    asyncio.get_event_loop().run_until_complete(dl.dl_loop())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\jochen\tradeRepublicExporter\hibiscus_tradeRepublicExporter\hibiscusexport.py", line 80, in dl_loop
    await self.tl.get_next_timeline_transactions()
  File "C:\Users\Elitebook G6\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pytr\timeline.py", line 30, in get_next_timeline_transactions
    await self.tr.timeline_transactions()
  File "C:\Users\Elitebook G6\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pytr\api.py", line 506, in timeline_transactions
    return await self.subscribe({"type": "timelineTransactions", "after": after})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elitebook G6\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pytr\api.py", line 322, in subscribe
    ws = await self._get_ws()
         ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elitebook G6\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pytr\api.py", line 301, in _get_ws
    self._ws = await websockets.connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elitebook G6\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\asyncio\client.py", line 442, in __await_impl__
    self.connection = await self.create_connection()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elitebook G6\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websockets\asyncio\client.py", line 368, in create_connection
    _, connection = await loop.create_connection(factory, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseEventLoop.create_connection() got an unexpected keyword argument 'extra_headers'

```

**Comment by littleyoda** [comment]
Wenn möglich probiere bitte mal eine ältere Python version.
Alles bis 3.10 sollte funktionieren. 
Das Problem schaue ich mir aber die Tage mal an.

**Comment by ajoe** [comment]
AH, ok. Habe es gerade mit Python 3.12 versucht. Gleicher Fehler. 
Edit: auch mit python 3.10 trat der fehler auf. 
bei allen installationen kam es mit pip zu diesen Fehlermeldungen:
[python3.10-win11-cmd.txt](https://github.com/user-attachments/files/18029873/python3.10-win11-cmd.txt)

**Comment by littleyoda** [comment]
Es lag an einer Inkompatibilität der websocket library, die von der pytr library genutzt wurde.
pytr benötigt websocket==13.

Ein neuer Checkout und ein neues anlegen der venv-Umgebung sollte das Problem lösen.
