### ISSUE TITLE
KeyError: self.tl.timeline_events[response['id']]

### ISSUE THREAD

**Issue by riker65** [littleyoda/hibiscus_tradeRepublicExporter#4]
Hi
habe leider einen Fehler:
python 3.13 nun 

habe vent activiert 

habe alles aktualisiert und weiß nicht was ich falsch mache?
bzw was die Fehler bedeuten? 
" There is no current event loop"

Danke fürs checken 
VG 

`10:45:16 Using hibiscus\tr2hibiscus.json
C:\Users\riker\hibiscus_tradeRepublicExporter\tr2hibiscusxml.py:124: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(dl.dl_loop())
10:45:16 Subscribing to #1 timeline transactions
10:45:16 Connecting to websocket ...
10:45:17 Connected to websocket ...
10:45:17 Received #1  timeline transactions
10:45:17 Received last relevant timeline transaction
10:45:17 Awaiting #1  timeline activity log
10:45:17 Received #1  timeline activity log
10:45:17 Received last relevant timeline activity log
10:45:17 All timeline details requested
Traceback (most recent call last):
  File "C:\Users\riker\hibiscus_tradeRepublicExporter\tr2hibiscusxml.py", line 130, in <module>
    main()
    ~~~~^^
  File "C:\Users\riker\hibiscus_tradeRepublicExporter\tr2hibiscusxml.py", line 124, in main
    asyncio.get_event_loop().run_until_complete(dl.dl_loop())
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\riker\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\riker\hibiscus_tradeRepublicExporter\hibiscusexport.py", line 98, in dl_loop
    event =  self.tl.timeline_events[response['id']]
             ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'b55188b5-35de-494e-ab44-a1f84d5124ae'
`

**Comment by littleyoda** [comment]
Probiere es nochmal mit einer aktuellen Version.

Der KeyError war das Hauptproblem.
`\Users\riker\hibiscus_tradeRepublicExporter\hibiscusexport.py", line 98, in dl_loop event =  self.tl.timeline_events[response['id']] ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^ KeyError: 'b55188b5-35de-494e-ab44-a1f84d5124ae' `

**Comment by riker65** [comment]
Hi, danke für die schnelle Hilfe,

scheint aber nicht richtig zu gehen.

mache ich was falsch? 

wie lange bleibt eigentlich die Websession offen?  Muss man sich da eventuell komplett ausloggen?

```
12:07:41 Web session resumed
12:07:41 Logged in
12:07:41 Using hibiscus\tr2hibiscus.json
12:07:41 Subscribing to #1 timeline transactions
12:07:41 Connecting to websocket ...
12:07:41 Connected to websocket ...
12:07:42 Received #1  timeline transactions
12:07:42 Received last relevant timeline transaction
12:07:42 Awaiting #1  timeline activity log
12:07:42 Received #1  timeline activity log
12:07:42 Received last relevant timeline activity log
12:07:42 All timeline details requested
```

die ersten beiden ids kommen schnell




```
`11:13:38 All timeline details requested
11:13:38 ID d11363eb-8fc4-4bb1-b244-daf786e281db not found in timeline!
11:13:38 ID 9f0d1af1-67ad-4c8d-aaf4-a15b98fe1f90 not found in timeline!'
```
dann dauert es etwas 


`11:13:38 All timeline details requested
11:13:38 ID d11363eb-8fc4-4bb1-b244-daf786e281db not found in timeline!
11:13:38 ID 9f0d1af1-67ad-4c8d-aaf4-a15b98fe1f90 not found in timeline!
Traceback (most recent call last):
  File "C:\Users\riker\hibiscus_tradeRepublicExporter\tr2hibiscusxml.py", line 136, in <module>
    main()
    ~~~~^^
  File "C:\Users\riker\hibiscus_tradeRepublicExporter\tr2hibiscusxml.py", line 127, in main
    asyncio.run(dl.dl_loop())
    ~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\riker\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\riker\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\riker\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\riker\hibiscus_tradeRepublicExporter\hibiscusexport.py", line 84, in dl_loop
    _subscription_id, subscription, response = await self.tr.recv()
                                               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\riker\hibiscus_tradeRepublicExporter\venv\Lib\site-packages\pytr\api.py", line 325, in recv
    response = await ws.recv()
               ^^^^^^^^^^^^^^^
  File "C:\Users\riker\hibiscus_tradeRepublicExporter\venv\Lib\site-packages\websockets\legacy\protocol.py", line 562, in recv
    await self.ensure_open()
  File "C:\Users\riker\hibiscus_tradeRepublicExporter\venv\Lib\site-packages\websockets\legacy\protocol.py", line 938, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)`

**Comment by riker65** [comment]
Hi, das wurde schon geschlossen, aber es geht leider noch nicht .

**Comment by littleyoda** [comment]
Ich dachte, die Änderung sollte das Problem beheben.

Führe bitte noch die aktuelle Version aus und schicke mir wieder das Logfile.

**Comment by riker65** [comment]
danke, 
ich hatte schon die aktuelle Version
Git pull : you already have latest

erhängt dann wieder hier 

`14:03:13 Web session resumed
14:03:13 Logged in
14:03:13 Using hibiscus\tr2hibiscus.json
14:03:13 Subscribing to #1 timeline transactions
14:03:13 Connecting to websocket ...
14:03:13 Connected to websocket ...
14:03:13 Received #1  timeline transactions
14:03:13 Received last relevant timeline transaction
14:03:13 Awaiting #1  timeline activity log
14:03:14 Received #1  timeline activity log
14:03:14 Received last relevant timeline activity log

14:03:14 All timeline details requested

14:03:14 ID 1e77586c-d52c-453a-b9a2-c75739e1ef71 not found in timeline!

14:03:14 ID c59f8dac-d861-4e6b-8a7a-eb852ef76d32 not found in timeline!`

**Comment by littleyoda** [comment]
Hatte vergessen die Änderungen zu pushen.
Probiere es bitte nochmal.

Irgendwie bringen die beiden Transaktionen das Programm durcheinander. 
Schauen wir mal, was die Logfile sagen.

**Comment by riker65** [comment]
hi,
danke nochmal, 
leider geht es immer noch nicht

`17:34:55 Connecting to websocket ...
17:34:56 Connected to websocket ...
17:34:56 Received #1  timeline transactions
17:34:56 Received last relevant timeline transaction
17:34:56 Awaiting #1  timeline activity log
17:34:56 Received #1  timeline activity log
17:34:56 Received last relevant timeline activity log

17:34:56 All timeline details requested
17:34:56 ID 3941995b-808c-486e-8a68-80c5090ae69d not found in timeline!
17:34:56 {"type": "timelineDetailV2", "id": "8bf259ef-73ac-44b8-8fca-4130a6f96196"}
17:34:56 ID e0f2d0a8-edee-4b6d-a8f8-5632e0a13803 not found in timeline!
17:34:56 {"type": "timelineDetailV2", "id": "d698d077-4a3c-41fb-acd0-aeff7cafe95c"}`

**Comment by littleyoda** [comment]
Für mich sieht es so aus, als ob das Problem in der von mir genutzten Library liegt.

Es wäre schön zu sehen, was das Tools der Library bei deinem Konto macht.


Falls du Lust und Nerven hast (für Linux):
```
mkdir pytr-tmp
cd pytr-tmp
 python -m venv  venv
 . venv/bin/activate
 pip install pytr
 pip install websockets=13
 pytr dl_docs docs
```

In dem Unterverzeichnis docs sollte danach eine Datei account_transactions.csv existieren.
Suche bitte in dieser Datei mal nach den beiden Buchungen, mit denen mein Programm Probleme hat.

Für mich wären folgende Dinge interessant:
1. Kommt pytr mit deinem Konto zu recht.
1a. Wenn nein, wäre ein Bugreport dort notwendig.
1b. Wenn ja, wie sehen die beiden Buchungen in der account_transactions.csv aus.

**Comment by riker65** [comment]
ich versuche das mal.
vorher ging es ja.

**Comment by riker65** [comment]
mkdir pytr-tmp soll  im Verzeichnis: hibiscus_tradeRepublicExporter gemacht werden? 

bin aber aktuell unter windows unterwegs
muss mal ubuntu checken

**Comment by littleyoda** [comment]
Ab besten komplett außerhalb. Einfach ein komplett neues Verzeichnis irgendwo anlegen.

**Comment by riker65** [comment]
also unter windows gibt es den Fehler:

er wollte unter windows auch:  pip install websockets==13


`18:21:42 Received last relevant timeline activity log
18:21:42 All timeline details requested
18:21:42   1/156: Deutsche Post -- None - 2024-12-11T12:48:44
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\riker\pytr-tmp\venv\Scripts\pytr.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\riker\pytr-tmp\venv\Lib\site-packages\pytr\main.py", line 266, in main
    asyncio.get_event_loop().run_until_complete(dl.dl_loop())
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\riker\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\riker\pytr-tmp\venv\Lib\site-packages\pytr\dl.py", line 85, in dl_loop
    await self.tl.process_timelineDetail(response, self)
  File "C:\Users\riker\pytr-tmp\venv\Lib\site-packages\pytr\timeline.py", line 130, in process_timelineDetail
    event = self.timeline_events[response["id"]]
            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '909c7c93-903c-4b76-8ea6-254c25d888a7'

(venv) C:\Users\riker\pytr-tmp>`

**Comment by littleyoda** [comment]
Also liegt der Fehler in der Library. 

Kann der Fehler damit zu tun haben?
https://github.com/pytr-org/pytr/issues/148
Die betroffenen haben alle die Gift-Funktion genutzt.

**Comment by riker65** [comment]
ja hatte mal ein gift gemacht

**Comment by littleyoda** [comment]
dann heißt es leider im Moment abwarten, bis es dort korrigiert wurde.

**Comment by riker65** [comment]
alles klar, danke für deine Hilfe 
top . VG 
wollte sowieso mal pytr checken 
merkwürdigerweise hatte er beim 2. versuch mehr transaktionen runtergeladen und dann kam erst der Fehler

**Comment by littleyoda** [comment]
Ich habe ein Repository erstellt, in dem die im Ticket vorgeschlagenen Änderungen enthalten sind.

Könntest du in deiner venv-Umgebung mal pytr aus meinem Repository ziehe und schauen, ob es  damit funktioiert?

`pip install -U git+https://github.com/littleyoda/pytr
`
